automirror:
  stage: deploy
  resource_group: production
  rules:
  - if: '$CI_PIPELINE_SOURCE == "schedule"'
  image: 
    name: $CI_REGISTRY_IMAGE:2.3.0
    entrypoint: ['']
  script: [/app/automirror --config "$CONFIG_FILE"]
