apiVersion: v1
kind: ConfigMap
metadata:
  name: automirror-config
  namespace: automirror

data:
  GITHUB_USERNAME: net7toulouse
  config.yaml: |-
    to: github.com
    from: git.inpt.fr

    defaults:
      topics: [sur github]
      subgroups:
        flatten: "-"

    orgs:
      inp-net:
        - from: net7
        - from: inp-net
          except: [inp-net/churros-ecosystem]
        - from: inp-net/churros-ecosystem
          prefix: churros-
        - from: churros
          prefix: churros-
          except: [churros/churros]
        - from: churros
          only: [churros/churros]

      tvn7: [from: tvn7]
      japan7: [from: japan7]
      7fault: [from: 7fault]
